### ISSUE TITLE
Fillet and Chamfer examples do not run.

### ISSUE THREAD

**Issue by delaneyj** [johnwebbcole/jscad-utils#2]
When selecting the link on the README get the error `TypeError: CSG.parseOptionAsFloat is not a function`.

**Comment by johnwebbcole** [comment]
Are you running from the site or from code?  Just checked the site, and it worked.

**Comment by johnwebbcole** [comment]
I’ve seen the error before, (and was surprised it was working for me).  I’ll see if I can’t get it fixed this weekend.

**Comment by delaneyj** [comment]
Thanks!
