### ISSUE TITLE
Unable to use with openjscad cli

### ISSUE THREAD

**Issue by paulhayes** [johnwebbcole/jscad-utils#4]
As openjscad cli no longer properly supports include, could you put an example of how to use this library using node modules rather than jscad files? ( as per the cli docs https://github.com/jscad/OpenJSCAD.org/tree/master/packages/cli ) 

I think this library is vital and I wish it got folded into the main jscad library.

**Comment by johnwebbcole** [comment]
There is a branch of the utilities built for es6 using rollup.  You may want to give that a try.

**Comment by paulhayes** [comment]
I only see a master and develop branch. Is it in a different repo?

**Comment by johnwebbcole** [comment]
First issue, I've moved my repo's to gitlab, so the up to date version is at https://gitlab.com/johnwebbcole/jscad-utils. Sorry.  I did just update the website on the gitlab version.

Second, It's in the master branch now, and the es6 version, built with rollup is published under @jwc/jscad-utils.

I also created a browserify test project using es6 built jscad-utils at https://gitlab.com/johnwebbcole/jscad-browserify-test.  Hopefully, these will get you moving in the right direction.  If you don't mind, would you move any issues to the gitlab site?  Thanks!

**Comment by paulhayes** [comment]
Ah thanks so much for getting back to me about this. 

I'm glad this is something your still actively developing.
